apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-zipkin-server
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-zipkin-server
  uid: 797321b9-a9ec-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8818440'
  generation: 75
  creationTimestamp: '2017-10-05T16:44:37Z'
  labels:
    app: omar-zipkin-server
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-zipkin-server
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-zipkin-server:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-zipkin-server@sha256:8322ed61a88d7ad55acdd880d07aa7bb1eb3b4da23a36279ae7b452b655ad203
  replicas: 1
  test: false
  selector:
    app: omar-zipkin-server
    deploymentconfig: omar-zipkin-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-zipkin-server
        deploymentconfig: omar-zipkin-server
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: omar-zipkin-server
          image: >-
            172.30.181.173:5000/o2/omar-zipkin-server@sha256:8322ed61a88d7ad55acdd880d07aa7bb1eb3b4da23a36279ae7b452b655ad203
          ports:
            - containerPort: 9411
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 65
  observedGeneration: 75
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-zipkin-server:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T19:42:36Z'
      lastTransitionTime: '2017-10-31T19:42:36Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-29T21:23:10Z'
      lastTransitionTime: '2017-11-29T21:23:07Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-zipkin-server-65" successfully rolled out
  readyReplicas: 1
